# .github/workflows/test.yml
name: Test and Common Checks

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: npm test

  common-checks:
    uses: cloudbees-pyang/helloworld-nodejs/.github/workflows/common-check.yml@main
